//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AgentInvoviceDetail
    {
        public int Id { get; set; }
        public Nullable<int> CatId { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> Discount { get; set; }
        public Nullable<double> Total { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string Status { get; set; }
        public Nullable<long> AgentId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<double> Percent { get; set; }
        public Nullable<double> Commission { get; set; }
        public Nullable<int> AgentInvoiceId { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual AgentInvoice AgentInvoice { get; set; }
        public virtual Category1 Category { get; set; }
        public virtual Product Product { get; set; }
        public virtual Service Service { get; set; }
    }
}
