//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Category()
        {
            this.Laundaries = new HashSet<Laundary>();
        }
    
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<byte> Delete { get; set; }
        public string Image { get; set; }
        public Nullable<double> Whole { get; set; }
        public Nullable<double> VIP { get; set; }
        public Nullable<double> Discount { get; set; }
        public string Start { get; set; }
        public string End { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Laundary> Laundaries { get; set; }
    }
}
