//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laundary
    {
        public int LaundryId { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<int> ServiceId { get; set; }
        public Nullable<int> CustomerId { get; set; }
        public string Status { get; set; }
        public string Date { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<double> PercentCommission { get; set; }
        public Nullable<double> Commission { get; set; }
        public string Time { get; set; }
        public Nullable<double> Price { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Invoice Invoice { get; set; }
        public virtual Service Service { get; set; }
        public virtual User User { get; set; }
    }
}
