//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permission
    {
        public int PermissionId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<byte> Create_Order { get; set; }
        public Nullable<byte> Setting { get; set; }
        public Nullable<byte> Sale_Report { get; set; }
        public Nullable<byte> Create_Customer { get; set; }
        public Nullable<byte> Create_Service { get; set; }
        public Nullable<byte> Backup { get; set; }
        public Nullable<byte> Create_User { get; set; }
        public Nullable<byte> Report_Monthly { get; set; }
        public Nullable<byte> Report_Daily { get; set; }
    
        public virtual User User { get; set; }
    }
}
