//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceType
    {
        public int ServiceTypeId { get; set; }
        public string ServiceTypeName { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> Auditor { get; set; }
        public string Status { get; set; }
    }
}
