//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laundry_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracker
    {
        public int id { get; set; }
        public string country { get; set; }
        public string ip { get; set; }
        public string location { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
    }
}
